# -*- coding: utf-8 -*-
"""ipynb_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HPvovLIVQnx49EPIgPhULQaySzgrVCke
"""

'This is a block of code'
print('very cool')



"""This is a text block

# New Section

**bold text**

*italicized text*

```
# This is formatted as code
```

[link text](https://colab.research.google.com/drive/1HPvovLIVQnx49EPIgPhULQaySzgrVCke?usp=sharing)

![red_sword.png](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA3UlEQVQ4jWNkIAO4cHD/J0cfGIA0/1+0GIw1WFhJMwim+aakAukGUE+zvAaNNIMUoocuWLO8Bl7NTMgcDRZWeBSB6N3isgy3fv1gUGPjYNB8epfhxp/f+KMdpGmaoDjYJpCNIDYhPzOiGxDEyQNmX/v9k2GysARBmzEkQIaAvHLjz2+GJ39+EXQ2iiS/nP9/Nm5FBuHbUxlkWNjAYoQMYUHWzCPuyvDm1nSG1xANYH9DDfqPyxAWWKhf5FYEa/758SpYIZIGvCmOEebnPT++Eo4mbC4A+RGEyQIMDAwATxKZBsx+sGIAAAAASUVORK5CYII=)

> Indented block

1.   List item
2.   List item

*   List item
*   List item

---
"""

#@title Default title text
#@markdown adfsjk

print('sup')